name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Hmerac/kubeval-action@1.1
      with:
        command: |
          echo "Running kubeval"
          kubeval -d manifests --strict